export const ZN_SUPPORTED_LOCALES = ['en-US', 'zh-CN'] as const
export type ZnSupportedLocale = (typeof ZN_SUPPORTED_LOCALES)[number]

export const ZN_LOCALE_PREFERENCES = ['system', ...ZN_SUPPORTED_LOCALES] as const
export type ZnLocalePreference = (typeof ZN_LOCALE_PREFERENCES)[number]

export type ZnDesktopLocaleState = {
  preference: ZnLocalePreference
  resolvedLocale: ZnSupportedLocale
  preferredSystemLanguages: string[]
}

const EN_US = {
  'common.ready': 'Ready',
  'common.connecting': 'Connecting',
  'common.offline': 'Offline',
  'common.refresh': 'Refresh',
  'common.checking': 'Checking...',
  'common.working': 'Working...',
  'common.applying': 'Applying...',
  'common.available': 'available',
  'common.unavailable': 'unavailable',
  'status.pending': 'pending',
  'status.running': 'running',
  'status.completed': 'completed',
  'status.failed': 'failed',
  'status.blocked': 'blocked',
  'status.cancelled': 'cancelled',
  'status.superseded': 'superseded',
  'status.waitingForUser': 'waiting for you',
  'stage.queued': 'queued',
  'stage.waiting': 'waiting',
  'stage.starting': 'starting',
  'stage.preparing': 'preparing',
  'stage.acting': 'acting',
  'stage.verifying': 'verifying',
  'stage.verified': 'verified',
  'stage.working': 'working',
  'stage.completed': 'completed',
  'stage.failed': 'failed',
  'stage.superseded': 'superseded',
  'stage.inspectionComplete': 'inspection complete',
  'sidebar.alwaysHere': 'Always here for you',
  'sidebar.newWork': 'New chat',
  'sidebar.navigation': 'Main navigation',
  'sidebar.pinned': 'Pinned',
  'sidebar.pin': 'Pin chat',
  'sidebar.unpin': 'Unpin chat',
  'sidebar.noPinned': 'Pinned chats will appear here',
  'sidebar.images': 'Images',
  'sidebar.scheduled': 'Scheduled tasks',
  'sidebar.plugins': 'Plugins',
  'sidebar.explore': 'Explore',
  'sidebar.comingSoon': 'This area is not connected yet.',
  'sidebar.soon': 'Soon',
  'sidebar.imagePrompt': 'Help me create an image: ',
  'sidebar.searchRecent': 'Search chats',
  'sidebar.recent': 'Recent',
  'sidebar.workspaces': 'Projects',
  'sidebar.localWork': 'Local work',
  'sidebar.noFolder': 'No folder attached',
  'sidebar.changeFolder': 'Change folder',
  'sidebar.attachFolder': 'Attach folder',
  'sidebar.detach': 'Detach',
  'sidebar.settings': 'Settings',
  'topbar.thisComputer': 'This computer',
  'topbar.chat': 'Chat',
  'topbar.work': 'Work',
  'topbar.recentWork': 'Recent work',
  'topbar.workDetails': 'Work details',
  'topbar.toggleSidebar': 'Toggle sidebar',
  'topbar.openSettings': 'Open Settings',
  'topbar.expandZn': 'Expand ZN',
  'topbar.compactZn': 'Compact ZN',
  'topbar.expand': 'Expand',
  'topbar.compact': 'Compact',
  'settings.eyebrow': 'ZN desktop',
  'settings.title': 'Settings',
  'settings.nav.personal': 'Personal',
  'settings.nav.app': 'App',
  'settings.language.title': 'General',
  'settings.language.description': 'Choose the language used across the ZN desktop app.',
  'settings.language.label': 'Interface language',
  'settings.language.system': 'Follow Windows',
  'settings.language.zhCN': '简体中文',
  'settings.language.enUS': 'English',
  'settings.language.systemDetected': 'Windows language: {{languages}}',
  'settings.background.title': 'Background service',
  'settings.background.description': 'ZN stays available when this window closes, so longer work can continue and reconnect here later.',
  'settings.background.refresh': 'Refresh status',
  'settings.background.technical': 'Technical details',
  'settings.background.waiting': 'Waiting for ZN...',
  'settings.models.title': 'API & models',
  'settings.models.description': 'Connect the model you want to talk with. ZN keeps local tools, permissions, memory, and durable Work behind it.',
  'settings.models.advancedActive': 'Advanced {{mode}} configuration is active{{routes}}.',
  'settings.models.routes': ' · {{count}} routes',
  'settings.models.advancedWarning': 'The simple editor will not overwrite advanced model routing configuration.',
  'settings.models.connectionReady': 'Connection available',
  'settings.models.connectionNeedsSetup': 'Connection needs setup',
  'settings.models.provider': 'Provider name',
  'settings.models.providerAria': 'Model provider',
  'settings.models.providerHelp': 'For example, OpenAI, Anthropic, Gemini, or a compatible service.',
  'settings.models.model': 'Model ID',
  'settings.models.modelAria': 'Provider model',
  'settings.models.modelPlaceholder': 'For example, gpt-4.1',
  'settings.models.modelHelp': 'Enter the model identifier supported by your provider.',
  'settings.models.baseUrl': 'API address',
  'settings.models.baseUrlAria': 'Provider API address',
  'settings.models.baseUrlPlaceholder': 'Leave blank to use the provider default',
  'settings.models.baseUrlHelp': 'For a local or compatible provider, enter its API address here.',
  'settings.models.credential': 'API key',
  'settings.models.credentialAria': 'Provider API key',
  'settings.models.credentialHelp': 'Your key is saved securely by ZN and is never shown again in this form.',
  'settings.models.credentialSaved': 'A key is already saved. Leave this blank to keep it, or enter a new key to replace it.',
  'settings.models.keepCredential': 'A key is saved · leave blank to keep it',
  'settings.models.optionalCredential': 'Leave blank if your local service does not require a key',
  'settings.models.securityDetails': 'Credential storage details',
  'settings.models.secureStore': 'Secure store: {{status}} · {{backend}}',
  'settings.models.save': 'Save changes',
  'settings.models.clearCredential': 'Clear credential',
  'settings.models.storedCredentialCleared': 'Saved API key cleared.',
  'settings.updates.title': 'Updates',
  'settings.updates.description': 'Check the ZN stable channel without source-repository credentials.',
  'settings.updates.check': 'Check for updates',
  'settings.updates.apply': 'Apply {{version}}',
  'settings.updates.updateFallback': 'update',
  'deepLink.received': 'Deep link received.',
  'deepLink.safe': 'Nothing was executed automatically.',
  'deepLink.dismiss': 'Dismiss',
  'home.eyebrow': 'Resident assistant',
  'home.title': 'What do you want to do?',
  'home.description': 'Talk to the model naturally. It decides whether to answer directly, use local capabilities, or continue durable Work for longer tasks.',
  'home.quickStartsAria': 'Quick starts',
  'home.openApp': 'Open an app',
  'home.cleanApp': 'Clean current app',
  'home.researchTopic': 'Research a topic',
  'home.reviewWorkspace': 'Review workspace',
  'home.attaching': 'Attaching...',
  'home.readinessAria': 'ZN readiness',
  'home.residentReady': 'Resident ready',
  'home.residentConnecting': 'Resident connecting',
  'home.residentOffline': 'Resident offline',
  'home.workspace': 'Workspace · {{name}}',
  'home.cognitionAvailable': 'Cognition available',
  'home.cognitionSetupNeeded': 'Cognition setup needed',
  'home.prompt.openApp': 'Open Chrome.',
  'home.prompt.cleanApp': 'Clean up the text in the current app.',
  'home.prompt.researchTopic': 'Research this topic and give me the useful evidence: ',
  'home.prompt.reviewWorkspace': 'Review the files in this workspace and tell me what needs attention.',
  'message.you': 'You',
  'message.activity': 'Activity',
  'message.executionEvidence': 'Execution evidence',
  'message.modelCalls_one': '{{count}} model call',
  'message.modelCalls_other': '{{count}} model calls',
  'message.technical': 'Technical details',
  'work.residentProgress': 'Resident progress · {{status}}',
  'work.workingOnIt': 'Working on it',
  'work.continuing': 'continuing work',
  'work.stop': 'Stop work',
  'work.stopping': 'Stopping...',
  'work.statusAria': 'Current work status',
  'work.accepted': 'Accepted by ZN',
  'work.verify': 'Verify result',
  'work.delegatedProgressAria': 'Delegated work progress',
  'work.delegated': 'Delegated work',
  'work.outsideUncertain': 'Outside-world effect is uncertain.',
  'work.noReplay': 'ZN will not replay this action automatically.',
  'work.whatDoing': 'What ZN is doing',
  'work.investigationRound': 'Investigation round {{round}} · {{status}}',
  'work.next': ' · next: {{next}}',
  'work.ok': 'ok',
  'work.failed': 'failed',
  'work.viewDetails': 'View details',
  'work.updated': 'Updated {{time}}',
  'result.title': 'Work result',
  'result.ready_one': 'Result is ready.',
  'result.ready_other': '{{count}} results are ready.',
  'result.view': 'View results',
  'composer.changeAttachedFolder': 'Change attached folder',
  'composer.attachFolder': 'Attach folder',
  'composer.changeFolder': 'Change folder',
  'composer.messageAria': 'Message ZN',
  'composer.placeholder': 'Tell ZN what you want to do...',
  'composer.sendAria': 'Send to ZN',
  'composer.background': 'ZN can keep working in the background · ',
  'composer.shortcut': 'Enter to send · Shift+Enter for newline',
  'details.closeWorkAria': 'Close work details',
  'details.panelAria': 'Work details',
  'details.title': 'Details',
  'details.currentWork': 'Current work',
  'details.closePanelAria': 'Close context panel',
  'details.workspace': 'Workspace',
  'details.change': 'Change',
  'details.detach': 'Detach',
  'details.noFolder': 'No local folder is attached to this work.',
  'details.attachFolder': 'Attach folder',
  'details.results': 'Results',
  'details.artifactsAria': 'Work artifacts',
  'details.noPreview': 'No textual preview available.',
  'details.previewTruncated': 'Preview is bounded; content was truncated.',
  'details.noResults': 'Relevant files, diffs and terminal output will appear here when this task produces them.',
  'details.residentStatus': 'Resident status',
  'details.restorePoints': 'Restore points',
  'details.restorePrompt': 'Open a Work or refresh to inspect retained restore points against current file reality.',
  'details.noRestorePoints': 'No retained restore points for this Work.',
  'details.restoreListAria': 'Work restore points',
  'details.retainedBytes': 'Retained {{count}} bytes',
  'details.restoreApproval': '{{proposal}} · user approval and fresh revalidation would be required',
  'details.restoreSafety': 'Changed, unchanged and unsafe targets remain inspection-only. Missing-target restore requires explicit preparation and approval with fresh resident revalidation.',
  'artifact.diff': 'Diff',
  'artifact.file': 'File',
  'artifact.terminal': 'Terminal',
  'artifact.other': 'Artifact',
  'restore.status.unchanged': 'Current target unchanged',
  'restore.status.changed': 'Current target changed',
  'restore.status.missing': 'Current target missing',
  'restore.status.unsupported': 'Current target cannot be compared safely',
  'restore.proposal.candidate': 'Restore candidate',
  'restore.proposal.conflict': 'Review current changes before any restore',
  'restore.proposal.missing': 'Review missing target before any restore',
  'restore.proposal.blocked': 'Restore proposal blocked',
  'restore.controls.description': 'This restores the retained exact bytes only if the target is still missing. It never overwrites a target that exists again.',
  'restore.controls.preparing': 'Preparing...',
  'restore.controls.prepare': 'Prepare restore',
  'restore.controls.restoring': 'Restoring...',
  'restore.controls.approve': 'Approve exact restore',
  'restore.application.approvalRequired': 'Prepared. Explicit approval is still required.',
  'restore.application.recoveryRequired': 'Interrupted restore needs fresh explicit approval.',
  'restore.application.completed': 'Restore completed and exact retained bytes were verified.',
  'restore.application.blocked': 'Restore is blocked by fresh reality.',
  'restore.application.state': 'Restore state: {{status}}',
  'delegated.kind.research': 'Research',
  'delegated.kind.coding': 'Coding',
  'delegated.kind.review': 'Review',
  'delegated.kind.work': 'Work',
  'delegated.stage.resultReady': 'result ready',
  'execution.memory': 'Resident memory',
  'execution.capability': 'Resident capability',
  'execution.investigation': 'Resident investigation',
  'execution.body': 'PC action',
  'execution.model': 'Model cognition',
  'execution.control': 'Resident control',
  'execution.budgetBlocked': 'Cognition budget blocked',
  'credential.unavailable': 'Credential status unavailable',
  'credential.secureStore': 'Credential stored in the resident secure store',
  'credential.environment': 'Credential supplied by {{environment}}',
  'credential.environmentFallback': 'provider environment',
  'credential.config': 'Legacy plaintext credential exists in config; replace it to migrate securely',
  'credential.secureStoreUnavailable': 'Credential reference exists, but this OS secure store is unavailable',
  'credential.none': 'No credential configured; local providers or provider environment variables can still work',
  'provider.checking.headline': 'Checking model connection',
  'provider.checking.detail': 'ZN is checking whether the conversation model is available.',
  'provider.ready.headline': 'Model connection ready',
  'provider.ready.detail': 'Model connection ready: {{detail}}',
  'provider.notConfigured.headline': 'No model configured yet',
  'provider.notConfigured.detail': 'Connect a provider and choose a model to start conversations. Local state and controls remain available without one.',
  'provider.unavailable.headline': 'Model connection is not available',
  'provider.unavailable.detail': 'The model is not available right now. Check the provider, model, API address and key.',
  'provider.attention.headline': 'Model setup needs attention',
  'provider.notice.ready': 'Model connection ready. {{detail}}',
  'provider.notice.notReady': 'Settings were saved, but this model is not available yet. {{detail}}',
  'error.desktopReconnect': '{{message}} ZN may keep working on this task while the desktop reconnects.',
  'error.residentUnavailableTitle': 'ZN is not connected yet',
  'error.residentUnavailableHint': 'This request was not confirmed. Reconnect before sending it again.',
  'error.residentUnavailable': 'I could not reach ZN’s background service.',
  'error.workStartFailed': 'I could not start this task. Your request was not accepted.',
  'error.reconnect': 'Reconnect',
  'workstation.returnToConversation': 'Back to conversation',
  'workstation.chatLabel': 'Chat',
  'workstation.openArtifact': 'Open result',
  'workstation.documentUnavailable': 'Document unavailable',
  'workstation.documentInvalid': 'This document could not be displayed safely.',
  'workstation.documentWorkspace': 'Document workspace',
  'workstation.documentOutline': 'Document outline',
  'workstation.document': 'Document',
  'workstation.sectionCount_one': '{{count}} section',
  'workstation.sectionCount_other': '{{count}} sections',
  'workstation.sectionLabel': 'Section {{index}}: {{heading}}',
  'workstation.nativeDocument': 'Document',
  'workstation.documentVersion': 'Document format v1',
  'workstation.slidesUnavailable': 'Slides preview unavailable',
  'workstation.slidesInvalid': 'This presentation could not be displayed safely.',
  'workstation.slidesWorkspace': 'Slides workspace',
  'workstation.slides': 'Slides',
  'workstation.slideLabel': 'Slide {{index}}: {{title}}',
  'workstation.currentWorkImage': 'Image from this work',
  'workstation.imageUnavailable': 'The referenced image is not available for preview.',
  'workstation.architectureDiagram': 'Architecture diagram',
  'error.missingDurableOutcome': 'Resident work ended without a durable work outcome',
  'tray.open': 'Open ZN',
  'tray.quit': 'Quit ZN',
  'dialog.runtimeUnavailable': 'ZN runtime unavailable'
} as const

export type ZnTranslationKey = keyof typeof EN_US

const ZH_CN: Record<ZnTranslationKey, string> = {
  'common.ready': '就绪',
  'common.connecting': '正在连接',
  'common.offline': '离线',
  'common.refresh': '刷新',
  'common.checking': '检查中...',
  'common.working': '处理中...',
  'common.applying': '应用中...',
  'common.available': '可用',
  'common.unavailable': '不可用',
  'status.pending': '等待中',
  'status.running': '执行中',
  'status.completed': '已完成',
  'status.failed': '失败',
  'status.blocked': '已阻止',
  'status.cancelled': '已取消',
  'status.superseded': '已被替代',
  'status.waitingForUser': '等待你处理',
  'stage.queued': '排队中',
  'stage.waiting': '等待中',
  'stage.starting': '正在启动',
  'stage.preparing': '正在准备',
  'stage.acting': '正在执行操作',
  'stage.verifying': '正在验证',
  'stage.verified': '已验证',
  'stage.working': '处理中',
  'stage.completed': '已完成',
  'stage.failed': '失败',
  'stage.superseded': '已被替代',
  'stage.inspectionComplete': '检查完成',
  'sidebar.alwaysHere': '随时都在',
  'sidebar.newWork': '新对话',
  'sidebar.navigation': '主导航',
  'sidebar.pinned': '置顶',
  'sidebar.pin': '置顶对话',
  'sidebar.unpin': '取消置顶',
  'sidebar.noPinned': '置顶的对话会显示在这里',
  'sidebar.images': '图像',
  'sidebar.scheduled': '定时任务',
  'sidebar.plugins': '插件',
  'sidebar.explore': '探索',
  'sidebar.comingSoon': '此功能尚未接入。',
  'sidebar.soon': '即将推出',
  'sidebar.imagePrompt': '帮我生成一张图片：',
  'sidebar.searchRecent': '搜索对话',
  'sidebar.recent': '最近',
  'sidebar.workspaces': '项目',
  'sidebar.localWork': '本机任务',
  'sidebar.noFolder': '未关联文件夹',
  'sidebar.changeFolder': '更换文件夹',
  'sidebar.attachFolder': '关联文件夹',
  'sidebar.detach': '解除关联',
  'sidebar.settings': '设置',
  'topbar.thisComputer': '这台电脑',
  'topbar.chat': '聊天',
  'topbar.work': '工作台',
  'topbar.recentWork': '最近任务',
  'topbar.workDetails': '任务详情',
  'topbar.toggleSidebar': '收起或展开侧栏',
  'topbar.openSettings': '打开设置',
  'topbar.expandZn': '展开 ZN',
  'topbar.compactZn': '收起 ZN',
  'topbar.expand': '展开',
  'topbar.compact': '收起',
  'settings.eyebrow': 'ZN 桌面端',
  'settings.title': '设置',
  'settings.nav.personal': '个人',
  'settings.nav.app': '应用',
  'settings.language.title': '常规',
  'settings.language.description': '选择 ZN 桌面端使用的界面语言。',
  'settings.language.label': '界面语言',
  'settings.language.system': '跟随 Windows',
  'settings.language.zhCN': '简体中文',
  'settings.language.enUS': 'English',
  'settings.language.systemDetected': 'Windows 语言：{{languages}}',
  'settings.background.title': '后台服务',
  'settings.background.description': '即使关闭这个窗口，ZN 仍会保持可用，较长的任务可以继续执行，之后再回到这里连接。',
  'settings.background.refresh': '刷新状态',
  'settings.background.technical': '技术详情',
  'settings.background.waiting': '正在等待 ZN...',
  'settings.models.title': 'API 与模型',
  'settings.models.description': '连接你要对话的模型。ZN 会在模型背后保留本地工具、权限、记忆和持续 Work。',
  'settings.models.advancedActive': '当前启用了高级 {{mode}} 配置{{routes}}。',
  'settings.models.routes': ' · {{count}} 条路由',
  'settings.models.advancedWarning': '简易编辑器不会覆盖高级模型路由配置。',
  'settings.models.connectionReady': '连接可用',
  'settings.models.connectionNeedsSetup': '连接需要设置',
  'settings.models.provider': '服务商名称',
  'settings.models.providerAria': '模型服务商',
  'settings.models.providerHelp': '例如 OpenAI、Anthropic、Gemini 或兼容服务。',
  'settings.models.model': '模型 ID',
  'settings.models.modelAria': '服务商模型',
  'settings.models.modelPlaceholder': '例如 gpt-4.1',
  'settings.models.modelHelp': '填写服务商支持的模型标识。',
  'settings.models.baseUrl': 'API 地址',
  'settings.models.baseUrlAria': '服务商 API 地址',
  'settings.models.baseUrlPlaceholder': '留空以使用服务商默认地址',
  'settings.models.baseUrlHelp': '使用本地或兼容服务时，请填写它提供的 API 地址。',
  'settings.models.credential': 'API 密钥',
  'settings.models.credentialAria': '服务商 API 密钥',
  'settings.models.credentialHelp': '密钥由 ZN 安全保存，不会再次显示在表单中。',
  'settings.models.credentialSaved': '已保存密钥。留空可保留当前密钥，输入新密钥则会替换。',
  'settings.models.keepCredential': '已保存密钥 · 留空可保留',
  'settings.models.optionalCredential': '本地服务不需要密钥时可以留空',
  'settings.models.securityDetails': '查看凭据存储详情',
  'settings.models.secureStore': '安全存储：{{status}} · {{backend}}',
  'settings.models.save': '保存更改',
  'settings.models.clearCredential': '清除凭据',
  'settings.models.storedCredentialCleared': '已清除保存的 API 密钥。',
  'settings.updates.title': '更新',
  'settings.updates.description': '无需源码仓库凭据即可检查 ZN 稳定版更新。',
  'settings.updates.check': '检查更新',
  'settings.updates.apply': '应用 {{version}}',
  'settings.updates.updateFallback': '更新',
  'deepLink.received': '已收到深链接。',
  'deepLink.safe': '没有自动执行任何操作。',
  'deepLink.dismiss': '关闭',
  'home.eyebrow': '常驻助手',
  'home.title': '你想让我做什么？',
  'home.description': '直接和模型聊。模型会先理解并决定下一步；需要操作时调用本地能力，较长任务再进入持续 Work。',
  'home.quickStartsAria': '快捷开始',
  'home.openApp': '打开应用',
  'home.cleanApp': '整理当前应用内容',
  'home.researchTopic': '研究一个主题',
  'home.reviewWorkspace': '检查工作区',
  'home.attaching': '正在关联...',
  'home.readinessAria': 'ZN 就绪状态',
  'home.residentReady': 'Resident 已就绪',
  'home.residentConnecting': 'Resident 正在连接',
  'home.residentOffline': 'Resident 已离线',
  'home.workspace': '工作区 · {{name}}',
  'home.cognitionAvailable': '认知资源可用',
  'home.cognitionSetupNeeded': '需要配置认知资源',
  'home.prompt.openApp': '打开 Chrome。',
  'home.prompt.cleanApp': '整理当前应用里的文字。',
  'home.prompt.researchTopic': '研究这个主题，并把有用的证据整理给我：',
  'home.prompt.reviewWorkspace': '检查这个工作区里的文件，告诉我哪些内容需要注意。',
  'message.you': '你',
  'message.activity': '活动',
  'message.executionEvidence': '执行证据',
  'message.modelCalls_one': '{{count}} 次模型调用',
  'message.modelCalls_other': '{{count}} 次模型调用',
  'message.technical': '技术详情',
  'work.residentProgress': 'Resident 进度 · {{status}}',
  'work.workingOnIt': '正在处理',
  'work.continuing': '继续执行',
  'work.stop': '停止任务',
  'work.stopping': '正在停止...',
  'work.statusAria': '当前任务状态',
  'work.accepted': 'ZN 已接收',
  'work.verify': '验证结果',
  'work.delegatedProgressAria': '委派任务进度',
  'work.delegated': '委派任务',
  'work.outsideUncertain': '外部世界的操作结果仍不确定。',
  'work.noReplay': 'ZN 不会自动重放这个操作。',
  'work.whatDoing': 'ZN 正在做什么',
  'work.investigationRound': '调查第 {{round}} 轮 · {{status}}',
  'work.next': ' · 下一步：{{next}}',
  'work.ok': '成功',
  'work.failed': '失败',
  'work.viewDetails': '查看详情',
  'work.updated': '更新于 {{time}}',
  'result.title': '任务结果',
  'result.ready_one': '结果已就绪。',
  'result.ready_other': '{{count}} 个结果已就绪。',
  'result.view': '查看结果',
  'composer.changeAttachedFolder': '更换已关联文件夹',
  'composer.attachFolder': '关联文件夹',
  'composer.changeFolder': '更换文件夹',
  'composer.messageAria': '给 ZN 发消息',
  'composer.placeholder': '告诉 ZN 你想做什么...',
  'composer.sendAria': '发送给 ZN',
  'composer.background': 'ZN 可以在后台继续工作 · ',
  'composer.shortcut': 'Enter 发送 · Shift+Enter 换行',
  'details.closeWorkAria': '关闭任务详情',
  'details.panelAria': '任务详情',
  'details.title': '详情',
  'details.currentWork': '当前任务',
  'details.closePanelAria': '关闭详情面板',
  'details.workspace': '工作区',
  'details.change': '更换',
  'details.detach': '解除关联',
  'details.noFolder': '当前任务未关联本地文件夹。',
  'details.attachFolder': '关联文件夹',
  'details.results': '结果',
  'details.artifactsAria': '任务产物',
  'details.noPreview': '没有可显示的文本预览。',
  'details.previewTruncated': '预览有长度限制，内容已截断。',
  'details.noResults': '当任务产生文件、差异或终端输出时，会显示在这里。',
  'details.residentStatus': 'Resident 状态',
  'details.restorePoints': '恢复点',
  'details.restorePrompt': '打开一个任务或刷新，以根据当前文件实际情况检查保留的恢复点。',
  'details.noRestorePoints': '当前任务没有保留的恢复点。',
  'details.restoreListAria': '任务恢复点',
  'details.retainedBytes': '已保留 {{count}} 字节',
  'details.restoreApproval': '{{proposal}} · 需要用户批准并重新验证当前状态',
  'details.restoreSafety': '已变化、未变化及无法安全比较的目标只提供检查。目标缺失时的恢复必须显式准备、批准，并由 Resident 重新验证。',
  'artifact.diff': '差异',
  'artifact.file': '文件',
  'artifact.terminal': '终端',
  'artifact.other': '产物',
  'restore.status.unchanged': '当前目标未变化',
  'restore.status.changed': '当前目标已变化',
  'restore.status.missing': '当前目标已缺失',
  'restore.status.unsupported': '无法安全比较当前目标',
  'restore.proposal.candidate': '恢复候选',
  'restore.proposal.conflict': '恢复前先检查当前变化',
  'restore.proposal.missing': '恢复前先检查缺失目标',
  'restore.proposal.blocked': '恢复提案已阻止',
  'restore.controls.description': '只有在目标仍然缺失时，才会恢复之前保留的精确字节；如果目标再次出现，绝不会覆盖它。',
  'restore.controls.preparing': '正在准备...',
  'restore.controls.prepare': '准备恢复',
  'restore.controls.restoring': '正在恢复...',
  'restore.controls.approve': '批准精确恢复',
  'restore.application.approvalRequired': '已准备完成，仍需要明确批准。',
  'restore.application.recoveryRequired': '中断的恢复需要重新明确批准。',
  'restore.application.completed': '恢复已完成，并验证了保留的精确字节。',
  'restore.application.blocked': '当前实际状态阻止了恢复。',
  'restore.application.state': '恢复状态：{{status}}',
  'delegated.kind.research': '研究',
  'delegated.kind.coding': '编码',
  'delegated.kind.review': '审查',
  'delegated.kind.work': '任务',
  'delegated.stage.resultReady': '结果已就绪',
  'execution.memory': 'Resident 记忆',
  'execution.capability': 'Resident 能力',
  'execution.investigation': 'Resident 调查',
  'execution.body': '电脑操作',
  'execution.model': '模型认知',
  'execution.control': 'Resident 控制',
  'execution.budgetBlocked': '认知预算已阻止',
  'credential.unavailable': '无法获取凭据状态',
  'credential.secureStore': '凭据已保存在 Resident 安全存储中',
  'credential.environment': '凭据由 {{environment}} 提供',
  'credential.environmentFallback': 'Provider 环境变量',
  'credential.config': '配置中存在旧版明文凭据；请重新保存以安全迁移',
  'credential.secureStoreUnavailable': '存在凭据引用，但当前操作系统安全存储不可用',
  'credential.none': '未配置凭据；本地 Provider 或 Provider 环境变量仍然可以工作',
  'provider.checking.headline': '正在检查模型连接',
  'provider.checking.detail': 'ZN 正在检查对话模型是否可用。',
  'provider.ready.headline': '模型连接已就绪',
  'provider.ready.detail': '已连接：{{detail}}',
  'provider.notConfigured.headline': '尚未配置模型',
  'provider.notConfigured.detail': '连接服务商并选择模型后即可开始对话；没有模型时，ZN 仍保留本地状态和控制能力。',
  'provider.unavailable.headline': '暂时无法连接模型',
  'provider.unavailable.detail': '模型暂时不可用，请检查服务商、模型、API 地址和密钥。',
  'provider.attention.headline': '模型配置需要处理',
  'provider.notice.ready': '模型连接已就绪。{{detail}}',
  'provider.notice.notReady': '设置已保存，但暂时无法使用该模型。{{detail}}',
  'error.desktopReconnect': '{{message}} ZN 可能仍在继续执行这个任务，桌面端会尝试重新连接。',
  'error.residentUnavailableTitle': 'ZN 还没有连接上',
  'error.residentUnavailableHint': '这项任务尚未确认收到。请先重连，再重新发送。',
  'error.residentUnavailable': '我暂时连不上 ZN 后台服务。',
  'error.workStartFailed': '我没能启动这项任务，后台尚未确认接受。',
  'error.reconnect': '重新连接',
  'workstation.returnToConversation': '返回对话',
  'workstation.chatLabel': '对话',
  'workstation.openArtifact': '打开结果',
  'workstation.documentUnavailable': '文档暂时无法显示',
  'workstation.documentInvalid': '这份文档未通过安全显示校验。',
  'workstation.documentWorkspace': '文档工作区',
  'workstation.documentOutline': '文档大纲',
  'workstation.document': '文档',
  'workstation.sectionCount_one': '{{count}} 个章节',
  'workstation.sectionCount_other': '{{count}} 个章节',
  'workstation.sectionLabel': '第 {{index}} 节：{{heading}}',
  'workstation.nativeDocument': '文档',
  'workstation.documentVersion': '文档格式 v1',
  'workstation.slidesUnavailable': '幻灯片暂时无法显示',
  'workstation.slidesInvalid': '这份演示文稿未通过安全显示校验。',
  'workstation.slidesWorkspace': '幻灯片工作区',
  'workstation.slides': '幻灯片',
  'workstation.slideLabel': '第 {{index}} 页：{{title}}',
  'workstation.currentWorkImage': '本次任务中的图片',
  'workstation.imageUnavailable': '引用的图片暂时无法预览。',
  'workstation.architectureDiagram': '架构图',
  'error.missingDurableOutcome': 'Resident 任务结束时没有产生持久化结果',
  'tray.open': '打开 ZN',
  'tray.quit': '退出 ZN',
  'dialog.runtimeUnavailable': 'ZN 运行时不可用'
}

export const ZN_DESKTOP_RESOURCES = {
  'en-US': { translation: EN_US },
  'zh-CN': { translation: ZH_CN }
} as const

export function isZnLocalePreference(value: unknown): value is ZnLocalePreference {
  return typeof value === 'string' && (ZN_LOCALE_PREFERENCES as readonly string[]).includes(value)
}

export function normalizeZnSupportedLocale(value: string): ZnSupportedLocale | null {
  const normalized = value.trim().replaceAll('_', '-').toLowerCase()
  if (!normalized) return null
  if (normalized === 'zh') return 'zh-CN'
  if (normalized.startsWith('zh-')) {
    const subtags = normalized.split('-').slice(1)
    if (subtags.includes('hant')) return null
    if (subtags.includes('hans')) return 'zh-CN'
    if (subtags.some((subtag) => subtag === 'tw' || subtag === 'hk' || subtag === 'mo')) return null
    if (subtags.some((subtag) => subtag === 'cn' || subtag === 'sg')) return 'zh-CN'
    return null
  }
  if (normalized === 'en' || normalized.startsWith('en-')) return 'en-US'
  return null
}

export function resolveZnLocale(
  preference: ZnLocalePreference,
  preferredSystemLanguages: readonly string[]
): ZnSupportedLocale {
  if (preference !== 'system') return preference
  for (const language of preferredSystemLanguages) {
    const resolved = normalizeZnSupportedLocale(language)
    if (resolved) return resolved
  }
  return 'en-US'
}

export function translateZnDesktop(
  locale: ZnSupportedLocale,
  key: ZnTranslationKey,
  values: Record<string, string | number> = {}
): string {
  const template = ZN_DESKTOP_RESOURCES[locale].translation[key] || EN_US[key]
  return template.replace(/\{\{(\w+)\}\}/g, (_match, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : ''
  )
}
